# %{PLACEHOLDER}% and !{PLACEHOLDER}! are placeholders that will be filled in
# at startup.
# - %{PLACEHOLDER}% can only refer to data that will be available regardless of
#   which script is run (i.e., other configuration values and command-line
#   arguments that are applicable to all scripts, like the startup time). Use
#   this form whenever possible.
# - !{PLACEHOLDER}! may refer to values that are only available for certain
#   scripts, such as the message title during MCR teardown. Use this form as
#   little as possible.

[ui]
theme = "dark"

[folder]
logs = "%{folder.home}%/Logs"
captions = "%{folder.home}%/Captions/%{args.startup_ymd}%"
archived_assets = "%{folder.assets_by_type}%/Archive"

[logging]
check_credentials         = "%{folder.logs}%/%{args.startup_timestamp}% check_credentials.log"
generate_slides           = "%{folder.logs}%/%{args.startup_timestamp}% generate_slides.log"
generate_slides_webdriver = "%{folder.logs}%/%{args.startup_timestamp}% generate_slides_webdriver.log"
download_pco_assets       = "%{folder.logs}%/%{args.startup_timestamp}% download_pco_assets.log"
mcr_setup                 = "%{folder.logs}%/%{args.startup_timestamp}% mcr_setup.log"
mcr_setup_webdriver       = "%{folder.logs}%/%{args.startup_timestamp}% mcr_setup_webdriver.log"
mcr_teardown              = "%{folder.logs}%/%{args.startup_timestamp}% mcr_teardown.log"
summarize_plan            = "%{folder.logs}%/%{args.startup_timestamp}% summarize_plan.log"
manual_test               = "%{folder.logs}%/%{args.startup_timestamp}% manual_test.log"

[captions]
original = "%{folder.captions}%/original.vtt"
final = "%{folder.captions}%/final.vtt"

[boxcast]
base_url = "https://rest.boxcast.com"
auth_base_url = "https://auth.boxcast.com"
rebroadcast_title = "Sunday Gathering Rebroadcast: %{args.startup_mdy}%"

[planning_center]
base_url = "https://api.planningcenteronline.com"
services_base_url = "https://api.planningcenteronline.com/services/v2"
# For help finding the service type for today's plan, see
# https://github.com/recc-tech/tech/wiki/Finding-the-Service-Type-for-a-Plan.
# Don't forget to enclose the service type ID in double quotes!
service_type_id = "882857"
# https://regex101.com/
kids_video_regex = "kids"
sermon_notes_regex = "^notes"
announcements_video_regex = "announcement"
default_speaker_name = "Lorenzo DellaForesta"

[vimeo]
# Maximum time since today's video was posted
new_video_hours = 3.0
# How many seconds to wait between re-checking that the new video is available
retry_seconds = 60.0
captions_type = "subtitles"
captions_language = "en-CA"
captions_name = "English (Canada)"
video_title = "%{args.startup_ymd}% | !{MESSAGE_SERIES}! | !{MESSAGE_TITLE}!"
# One way of finding this is to export a recording from BoxCast to Vimeo and,
# in the dev tools network tab, check the request payload
user_id = "viac_bvteonscuog48b2lnilu"

[vmix]
base_url = "http://192.168.0.107:8088/api"
preset_path = "%{folder.home}%/vMix Presets/%{args.startup_ymd}% Live.vmix"
# IDs of important inputs
kids_connection_list_key = "377a5427-91fa-4cbc-80ee-1bb752a5e364"
announcements_list_key = "e1546910-ee02-4ce5-8733-3d20f2dcce3b"
pre_stream_title_key = "002e27ec-9ef5-4f47-9ff3-c49d346a8aaa"
speaker_title_key = "9d2614a9-26ff-42a0-95f2-220d82370606"
host_title_key = "407171aa-af67-4d25-8ab5-1659176fc79d"
extra_presenter_title_key = "8e81a0df-26b2-42ab-a5ae-5c79199a53d7"

[api]
# After this many seconds, a request is assumed to have failed
timeout_seconds = 15.0

[plan_summary]
# Where to save the summary
file = "%{folder.plan_summaries}%/%{args.startup_ymd}%-summary.html"
# Categories of notes that will be shown (e.g., visuals is relevant, vocals is
# probably not)
note_categories = ["Visuals"]

[slides]
message_notes_filename = "message-notes.txt"
lyrics_filename = "lyrics.txt"
blueprints_filename = "blueprints.json"
image_width = 1920
image_height = 1080
font_family = ["Helvetica", "Calibri", "sans-serif"]

	[slides.fullscreen_message]
	background = "white"

		[slides.fullscreen_message.body]
		x = 100
		y = 100
		width = 1720
		height = 880
		horiz_align = "center"
		vert_align = "center"
		text_colour = "#333333"
		line_spacing = 1.75

			[slides.fullscreen_message.body.font]
			style = "normal"
			bold = true
			min_size = 36
			max_size = 72

	[slides.fullscreen_scripture]
	background = "white"

		[slides.fullscreen_scripture.body]
		x = 100
		y = 100
		width = 1720
		height = 680
		horiz_align = "left"
		vert_align = "top"
		text_colour = "#333333"
		line_spacing = 1.75

			[slides.fullscreen_scripture.body.font]
			style = "normal"
			bold = true
			min_size = 36
			max_size = 72

		[slides.fullscreen_scripture.footer]
		x = 100
		y = 880
		width = 1720
		height = 100
		horiz_align = "right"
		vert_align = "center"
		text_colour = "dimgrey"
		line_spacing = 1.75

			[slides.fullscreen_scripture.footer.font]
			style = "oblique"
			bold = false
			min_size = 30
			max_size = 60

	[slides.lowerthird_message]
	background = "#00000000"

		[slides.lowerthird_message.rectangle]
		x = 0
		y = 850
		width = 1920
		height = 200
		colour = "#00000088"

		[slides.lowerthird_message.body]
		x = 25
		y = 850
		width = 1870
		height = 200
		horiz_align = "center"
		vert_align = "center"
		text_colour = "white"
		line_spacing = 2

			[slides.lowerthird_message.body.font]
			style = "normal"
			bold = true
			min_size = 24
			max_size = 48

	[slides.lowerthird_scripture]
	background = "#00000000"

		[slides.lowerthird_scripture.rectangle]
		x = 0
		y = 825
		width = 1920
		height = 225
		colour = "#00000088"

		[slides.lowerthird_scripture.body]
		x = 0
		y = 825
		width = 1870
		height = 160
		horiz_align = "left"
		vert_align = "top"
		text_colour = "white"
		line_spacing = 1.5

			[slides.lowerthird_scripture.body.font]
			style = "normal"
			bold = true
			min_size = 24
			max_size = 48

		[slides.lowerthird_scripture.footer]
		x = 25
		y = 985
		width = 1870
		height = 50
		horiz_align = "right"
		vert_align = "center"
		text_colour = "#DDDDDD"
		line_spacing = 1

			[slides.lowerthird_scripture.footer.font]
			style = "oblique"
			bold = false
			min_size = 20
			max_size = 40
