station = "mcr"

[folder]
home = "D:/Users/Tech/Documents"
assets_by_service = "%{folder.home}%/vMix Assets/By Service/%{args.startup_ymd}%"
assets_by_type = "%{folder.home}%/vMix Assets/By Type"
images = "%{folder.assets_by_type}%/Images"
videos = "%{folder.assets_by_type}%/Videos"
plan_summaries = "%{folder.assets_by_service}%"
