# This workflow periodically creates an issue reminding us to review the
# documentation.

on:
  schedule:
    # https://crontab.guru/#15_1_1_1,3,5,7,9,11_*
    # Unfortunately it seems a bit tough to schedule something for the first
    # Sunday of the month: https://stackoverflow.com/a/51343686
    - cron: '15 1 1 1,3,5,7,9,11 *'
  workflow_dispatch:

name: Create issue for documentation review

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v2
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ./checklists/documentation-review.md
