on:
  schedule:
    # https://crontab.guru/#15_1_*_*_SUN
    - cron: '15 1 * * SUN'
  # Let people trigger the workflow manually for testing purposes
  workflow_dispatch:

name: Create issues for setup and teardown checklists

permissions:
  contents: read
  issues: write

jobs:
  # Find all the checklists in /checklists/
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.1
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "../../checklists"
          ext: ".md"
  test:
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    runs-on: ubuntu-latest
    steps:
      - name: Output results
        run: |
          echo ${{ matrix.paths }}

# jobs:
#   
#   list-files:
#     runs-on: ubuntu-latest
#     outputs:
#       paths: ${{ steps.list-files.outputs.paths }}
#     steps:
#       - name: List files
#         id: list-files
#         uses: mirko-felice/list-files-action@v3.0.1
#         with:
#           repo: ${{ github.repository }}
#           ref: ${{ github.ref }}
#           path: "/checklists"
#           ext: ".md"
#   # Create an issue for each checklist
#   create-issues:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: MCR video setup
#         uses: JasonEtco/create-an-issue@v2
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           filename: checklists/mcr-video-setup.md
#       - name: MCR video teardown
#         uses: JasonEtco/create-an-issue@v2
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           filename: checklists/mcr-video-teardown.md
