# This workflow generates an issue for each markdown file in the /checklists/ directory.
# This allows us to check off the checkboxes and keep track of what steps are done.

on:
  schedule:
    # https://crontab.guru/#15_9_*_*_SUN
    # 9:15 UTC is either 5:15 or 4:15 eastern time, depending on whether we're currently in daylight savings time
    - cron: '15 9 * * SUN'
  # Let people trigger the workflow manually (for testing or for gatherings that are not on a Sunday)
  workflow_dispatch:

name: Create issues for setup and teardown checklists

permissions:
  contents: read
  issues: write

jobs:
  # Find all the checklists in /checklists/
  list-files:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.1
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "./checklists/weekly/"
          ext: ".md"
  # Create an issue for each checklist
  create-issues:
    runs-on: ubuntu-latest
    needs: list-files
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}
    steps:
      - uses: actions/checkout@v2
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ${{ matrix.paths }}
