# This worklow tags the latest commit on main with the current date.
# This makes it easy to roll back to the code that was used on a previous
# Sunday in case something is not working.

name: Tag releases

on:
  schedule:
    # https://crontab.guru/#15_9_*_*_SUN
    # 9:15 UTC is either 5:15 or 4:15 eastern time, depending on whether we're currently in daylight savings time
    - cron: '15 9 * * SUN'
  # Let people trigger the workflow manually (for testing or for gatherings that are not on a Sunday)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-tags: true
      - name: Check if latest commit is already tagged
        id: check_existing_tag
        shell: bash
        run: |
          # set +e is necessary to prevent the whole job from failing if git
          # describe exits with non-zero status.
          set +e
          git describe main --tags --exact-match
          # git describe will return non-zero status if it fails to find a tag
          if [[ "$?" == 0 ]]; then
            echo "ALREADY_TAGGED=true" >> $GITHUB_OUTPUT
          else
            echo "ALREADY_TAGGED=false" >> $GITHUB_OUTPUT
          fi
      - name: Get today's date
        id: get_date
        run: |
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Get SHA hash for main
        id: main_sha
        run: |
          echo "SHA=$(git rev-parse main)" >> $GITHUB_OUTPUT
      # https://stackoverflow.com/a/64479344
      - name: Create tag
        if: steps.check_existing_tag.outputs.ALREADY_TAGGED == 'false'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              ref:   'refs/tags/${{steps.get_date.outputs.TODAY}}',
              sha:   '${{ steps.main_sha.outputs.SHA }}'
            });
